### ISSUE TITLE
How to split data?

### ISSUE THREAD

**Issue by Exspectate** [Skill3t/IEC61850-MMS-Fuzzer#2]
Should I split my pcap into small pieces by services?
I don't understand how to find the piont to split pcapfile
thank you

**Comment by Skill3t** [comment]
Yes you need one file with the Association. And for each services and each logical node a seperat one. For Instance 0_00_associat.pcap and one file 1_14_F201CTRL_QA1CSWI8_Pos.pcap. 14 is  SBO control with enhanced security.

**Comment by Skill3t** [comment]
A Association step look like this.
<img width="1325" alt="grafik" src="https://user-images.githubusercontent.com/6004614/60816460-17551c00-a19a-11e9-8753-68a42e30591c.png">

**Comment by jjchromik** [comment]
I would also like to ask about how to split the data. Is the way of working the following: 
- generate some MMS data. 
- split the traffic in the pieces as explained in the Readme.
- use the spit pieces to fuzz the device? 

I am new with MMS so I also am not sure what Association is. Could you please elaborate? 
Is it possible to write a piece of code that does this splitting? 

I would really appreciate if you could give an example pcap with a single MMS packet and instruction how to use it for fuzzing.

**Comment by Skill3t** [comment]
Hi so yes the Fuzzer works excactly how you discripe it. I wrote a small Programm to do the connection and splitting thing but the problem is I use a paid licens to do so. So I can not share it with you. The Easeast way is to use a standard IEC61850 Tool like IED Scout [IEDSCout](https://www.omicronenergy.com/de/produkte/iedscout/) from Omicron. But the licens are a bit pricy. They may offer a 30 day trail. Then you run in parallel wireshark an capture the whole traffic. You can mark the needet MMS Packages in Wireshark and export them. 
Association is the initial connection. You can see an Association example in the pictur above. First you initiate a normal 3 Way TCP Handshake then you send an COTP Package with an initiate-Request and after a respone you have to send an MMS initiate-Request. After the response  the MMS connection is establiched. But IEDScout will do the work for you, you just use the Fuzzer do replay this packages.  I have multiple pcaps but they fit und spezial devices so they will probably not fit on yours.

**Comment by jjchromik** [comment]
Hi, thank you for your response. 
In other words: 

**Step 1** is to generate MMS data. This data can be generated by capturing the network traffic and connecting the tools like IEDScout to the MMS device. 

**Step 2** is to split the captured file into small PCAP files. I think this part could be automated, correct? Have input a PCAP file captured during the tests done with IEDScout, and then output various X_YY_ZZ.pcap files. 

**Step 3** is to use your fuzzer. 

I think the most difficult for me is to understand the step 2. 
Would an X_00_ZZ.pcap file contain all the packets as in the capture you presented? Or only packets 13 and 15? Or only 13? 

Could you also please elaborate what X (sequential number) is? 
And ZZ (logical node reference)? 
If I have only one IED that uses MMS, will I have multiple Xs and ZZs or just one X and one ZZ? 

I appreciate your help.

**Comment by Skill3t** [comment]
Hi,
so Step 1-3 are correct. So the Fuzzer use the Wireshark 'cotp' filter. So you do not need the tcp traffic but is also do not matter if its in the file. More important is that the first package in the filter cotp is the initiate-Request and the 3. is the MMS initiate-Request. Have a look to the connection module. The connect will find out the server ip and establish a TCP-Connection to port 102 (MMS). Then it will reply the correct packages do not worry if there is more in the pcap. The connect filer out what it needs. 

X is just a unique int to sort the test and process step by step. 
ZZ is just needet for the PDF dokumentation. You can fill in a rendom string to later identify your tests.

With one IED you will defently have multiple X for each data refrence you want to test. You can test each data attribute in you device but not all makes sence to check. And to identify the test later you will give each X a naming ZZ. In my opinon it only makes sense to Fuzz DA's with the FC 'SP, CF, DC, SV, CO, CF, SG, SE'. For instance on the FC MX you can only read information where is the vector to crash / manipulate the device. You need to wirte date to the device. But fell free to prove me wrong ^^. 

One Idea is to generate the files with a local SCADA ore any other client like a gateway or so on and a switch with a mirror port. So you do not need any tool but the splitting is more difficult then.
